name: docs

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Test build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install --upgrade -r docs/requirements.txt
      - name: Build documentation with Sphinx
        run: |
            make -C docs clean
            make -C docs -nWT -b dummy
